coverage:
  precision: 2
  round: down
  range: "50...95"

status:
  project:
    default:
      enabled: yes
      target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no