language: java

jdk: 
  - oraclejdk11

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11

script: mvn clean verify

cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
