language: java

jdk: 
  - oraclejdk11

services:
  - xvfb

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11

before_install:
  - export DISPLAY=:99.0
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install at-spi2-core

script: 
  - mvn clean verify

cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
