#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - dev
    - master

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
  author: marcsllite@gmail.com   

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  # Linux Debugging
  # APPVEYOR_SSH_BLOCK: true
  # Mac Debugging
  APPVEYOR_VNC_BLOCK: true
  MAVEN_VERSION: 3.6.3
  WIN_JDK: C:\Program Files\Java\jdk11
  GITHUB_TOKEN:
    secure: SikYTKBlWZ9T6Ep9yw85sLN3+5ryqKyc8YzjTZgnK5adhMWMPvme0gMrLTgtG8ah
  CODECOV_TOKEN:
    secure: zQd1mZd+Bl9Ev/rUgtx5eozOVW79Hcpp2+a8U01ij4hESsUrYJIuK29ZPmlmS3ql
  matrix:
    # - job_name: Windows build
    #   appveyor_build_worker_image: Visual Studio 2019

    - job_name: Mac build
      appveyor_build_worker_image: macOs
      _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=tk2"

    # - job_name: Linux build
    #   appveyor_build_worker_image: Ubuntu2004
    #   _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=tk2"

stack: jdk 11

for:
  # WINDOWS BUILD #
  # -
  #   matrix:
  #     only:
  #       - job_name: Windows build

  #   install:
  #     - set JDK_HOME=%WIN_JDK%
  #     # JAVA_HOME is used by Maven
  #     - set JAVA_HOME=%WIN_JDK%
  #     - set PATH=%JDK_HOME%;%JDK_HOME%\bin;%PATH%

  #   build_script:
  #     - cmd: mvn clean verify
      
  #   test_script:
  #     - ps: $wc = New-Object 'System.Net.WebClient';
  #           foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports -include TEST-*.xml -name) { `
  #             $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\target\surefire-reports\$file)); }
  
  #   on_success:
  #     - ps: Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe; 
  #           .\codecov.exe -t $CODECOV_TOKEN

  #   cache:
  #     - '%MAVEN_HOME% -> pom.xml'
  #     - '%UserProfile%\.m2 -> pom.xml'

  # MAC BUILD #
  -
    matrix:
      only:
        - job_name: Mac build

    install:
      - sh: brew install maven

    build_script:
      - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
      - sh: mvn clean verify

    test_script:
      - sh: |
          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
    
    on_success:
      - sh: curl -Os https://uploader.codecov.io/latest/macos/codecov &&
            chmod +x codecov &&
            ./codecov -t $CODECOV_TOKEN

    cache:
      - $HOME/.m2 -> pom.xml
      
  # LINUX BUILD #
  # -
  #   matrix:
  #     only:
  #       - job_name: Linux build

  #   install:
  #     - sh: sudo apt-get -y install libcanberra-gtk-module
  #     - sh: wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P /tmp &&
  #           sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt && 
  #           sudo update-alternatives --install /usr/bin/mvn mvn /opt/apache-maven-3.6.3/bin/mvn 363
  #     - sh: Xvfb :99 &>/dev/null &
  #           export DISPLAY=:99

  #   build_script:
  #     - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  #     - sh: mvn clean verify

  #   test_script:
  #     - sh: |
  #         find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
    
  #   on_success:
  #     - sh: curl -Os https://uploader.codecov.io/latest/linux/codecov &&
  #           chmod +x codecov &&
  #           ./codecov -t $CODECOV_TOKEN

  #   cache:
  #     - $HOME/.m2 -> pom.xml

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - marcsllite@gmail.com
    on_build_status_changed: true