#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - dev
    - master

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
  author: marcsllite@gmail.com   

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  # Linux Debugging
  # APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGx6AiZps++og4I04DyhDXp6ExBV68jkrGzqvWw9mqu03vHW4KIglXjiTm+WXb0wkpisiQCmnQLXYh6QgMzgA24QZ8PZS8KTzqqb/5xlAl4HoIu4yTXzi/cxfc0+WqjpSRRfC1GPD2OXsXvfufzl3RDKV6YeYaetVpYuc+OZpCsuDm01c6mKmwuzK0+QaaQKL3MLLwYdLNm0XIRatvXuEwiDl4IlEAwLMJqVCs/+JFxThSSt95VuLG2HrGdwQ4jCi2mK28Udw1u/ae5SPDSz1KhfoBZqv03kfAJmzjYZ9Ro4NMPQVCz26jYHYWHOKcP0CfQre6VaZBDF6CeM3sR2vcrb+oDmL+UYDHyVVMQlhuklU5CJhd9BQKqYonJPCWynVNVgN6vght8gTERRSL956ywSj/RKQNPISTf2zRTCfR0uK6AT33ZEQXDkJ0B8F0tIkz4V672KjJaQT6fDS/grOV4/SxaEKrKHauOcDAOHhLXDKRcpM2Ne1yAh7kiP7BgG0= marcsllite@marcsllte-linux
  # APPVEYOR_SSH_BLOCK: true
  # Mac Debugging
  # APPVEYOR_VNC_BLOCK: true
  # Windows Debugging
  APPVEYOR_RDP_PASSWORD:
    secure: Jrjywnv+EXOkMCVKLVB+lA==
  MAVEN_VERSION: 3.6.3
  WIN_JDK: C:\Program Files\Java\jdk11
  GITHUB_TOKEN:
    secure: SikYTKBlWZ9T6Ep9yw85sLN3+5ryqKyc8YzjTZgnK5adhMWMPvme0gMrLTgtG8ah
  CODECOV_TOKEN:
    secure: zQd1mZd+Bl9Ev/rUgtx5eozOVW79Hcpp2+a8U01ij4hESsUrYJIuK29ZPmlmS3ql
  matrix:
    - job_name: Windows build
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: Mac build
      appveyor_build_worker_image: macos-monterey

    - job_name: Linux build
      appveyor_build_worker_image: Ubuntu2004

stack: jdk 11

for:
  # WINDOWS BUILD #
  -
    matrix:
      only:
        - job_name: Windows build

    install:
      - set JDK_HOME=%WIN_JDK%
      # JAVA_HOME is used by Maven
      - set JAVA_HOME=%WIN_JDK%
      - set PATH=%JDK_HOME%;%JDK_HOME%\bin;%PATH%

    build_script:
      - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      # - cmd: mvn clean verify -e -X
      
    test_script:
      - ps: $wc = New-Object 'System.Net.WebClient';
            foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports -include TEST-*.xml -name) { `
              $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\target\surefire-reports\$file)); }
  
    on_success:
      - ps: Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe; 
            .\codecov.exe -t $CODECOV_TOKEN

    cache:
      - '%MAVEN_HOME% -> pom.xml'
      - '%UserProfile%\.m2 -> pom.xml'

  # MAC BUILD #
  -
    matrix:
      only:
        - job_name: Mac build

    install:
      - sh: export HOMEBREW_NO_INSTALL_CLEANUP=1 &&
            export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
      - sh: brew install mvnvm &&
            mvn -d clean package

    build_script:
      # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
      - sh: mvn clean verify

    test_script:
      - sh: |
          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
    
    on_success:
      - sh: curl -Os https://uploader.codecov.io/latest/macos/codecov &&
            chmod +x codecov &&
            ./codecov -t $CODECOV_TOKEN

    cache:
      - $HOME/.m2 -> pom.xml
      
  # LINUX BUILD #
  -
    matrix:
      only:
        - job_name: Linux build

    install:
      - sh: sudo apt-get -y install libcanberra-gtk-module
      - sh: wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.tar.gz -P /tmp &&
            sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt && 
            sudo update-alternatives --install /usr/bin/mvn mvn /opt/apache-maven-3.6.3/bin/mvn 363
      - sh: Xvfb :99 &>/dev/null &
            export DISPLAY=:99

    build_script:
      # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
      - sh: mvn clean verify

    test_script:
      - sh: |
          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
    
    on_success:
      - sh: curl -Os https://uploader.codecov.io/latest/linux/codecov &&
            chmod +x codecov &&
            ./codecov -t $CODECOV_TOKEN

    cache:
      - $HOME/.m2 -> pom.xml

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - marcsllite@gmail.com
    on_build_status_changed: true