#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - dev
    - master

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
  author: marcsllite@gmail.com   

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  # Linux/Mac SSH Debugging
  # APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGx6AiZps++og4I04DyhDXp6ExBV68jkrGzqvWw9mqu03vHW4KIglXjiTm+WXb0wkpisiQCmnQLXYh6QgMzgA24QZ8PZS8KTzqqb/5xlAl4HoIu4yTXzi/cxfc0+WqjpSRRfC1GPD2OXsXvfufzl3RDKV6YeYaetVpYuc+OZpCsuDm01c6mKmwuzK0+QaaQKL3MLLwYdLNm0XIRatvXuEwiDl4IlEAwLMJqVCs/+JFxThSSt95VuLG2HrGdwQ4jCi2mK28Udw1u/ae5SPDSz1KhfoBZqv03kfAJmzjYZ9Ro4NMPQVCz26jYHYWHOKcP0CfQre6VaZBDF6CeM3sR2vcrb+oDmL+UYDHyVVMQlhuklU5CJhd9BQKqYonJPCWynVNVgN6vght8gTERRSL956ywSj/RKQNPISTf2zRTCfR0uK6AT33ZEQXDkJ0B8F0tIkz4V672KjJaQT6fDS/grOV4/SxaEKrKHauOcDAOHhLXDKRcpM2Ne1yAh7kiP7BgG0= marcsllite@marcsllte-linux
  # APPVEYOR_SSH_BLOCK: true
  # Mac VNC Debugging
  # APPVEYOR_VNC_BLOCK: true
  # APPVEYOR_VNC_PASSWORD:
  #   secure: aKkTdpvVR2UQkHyLAoM15w==
  # Windows RDP Debugging
  # APPVEYOR_RDP_PASSWORD:
  #   secure: Jrjywnv+EXOkMCVKLVB+lA==
  APP_VERSION: 1.0.0.$APPVEYOR_BUILD_NUMBER
  MAVEN_VERSION: 3.6.3
  WIN_JDK: C:\Program Files\Java\jdk17
  GITHUB_TOKEN:
    secure: SikYTKBlWZ9T6Ep9yw85sLN3+5ryqKyc8YzjTZgnK5adhMWMPvme0gMrLTgtG8ah
  CODECOV_TOKEN:
    secure: zQd1mZd+Bl9Ev/rUgtx5eozOVW79Hcpp2+a8U01ij4hESsUrYJIuK29ZPmlmS3ql
  matrix:
    # https://www.appveyor.com/docs/windows-images-software/
    - job_name: Windows build
      appveyor_build_worker_image: Visual Studio 2022

    # https://www.appveyor.com/docs/linux-images-software/
    - job_name: Linux build
      appveyor_build_worker_image: Ubuntu2204

    # https://www.appveyor.com/docs/macos-images-software/
    - job_name: Mac build
      appveyor_build_worker_image: macos-sonoma

stack: jdk 17

for:
  # WINDOWS BUILD #
  -
    matrix:
      only:
        - job_name: Windows build

    install:
      - set JDK_HOME=%WIN_JDK%
      # JAVA_HOME is used by Maven
      - set JAVA_HOME=%WIN_JDK%
      - set PATH=%JDK_HOME%\bin;%PATH%

    build_script:
      # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      - cmd: mvn clean verify -Dbuild.version=1.0.0.%APPVEYOR_BUILD_NUMBER%
      
    on_finish:
      - ps: $wc = New-Object 'System.Net.WebClient';
          if(Test-Path -Path "$env:APPVEYOR_BUILD_FOLDER/target/surefire-reports") { `
            foreach($file in get-childItem "$env:APPVEYOR_BUILD_FOLDER/target/surefire-reports" -include TEST-*.xml -name) { `
              $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path ".\target\surefire-reports\$file")); }}
      - ps: $wc = New-Object 'System.Net.WebClient';
          if(Test-Path -Path "$env:APPVEYOR_BUILD_FOLDER/target/failsafe-reports") { `
            foreach($file in get-childItem "$env:APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -include TEST-*.xml -name) { `
              $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path ".\target\failsafe-reports\$file")); }}

    on_failure:
      - ps: if(Test-Path -Path "$env:APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged") { `
          Push-AppveyorArtifact Resolve-Path "$env:APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged"; }

    on_success:
      - ps: if(Test-Path -Path "$env:APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$env:APPVEYOR_BUILD_NUMBER.exe") { `
          Push-AppveyorArtifact Resolve-Path "$env:APPVEYOR_BUILD_FOLDER/target/1.0.0.$env:APPVEYOR_BUILD_NUMBER.exe"; } else {  Write-Host "Failed to locate $env:APPVEYOR_BUILD_FOLDER/target/1.0.0.$env:APPVEYOR_BUILD_NUMBER.exe"  }
      - ps: try { `
          Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe;
          .\codecov.exe -t $CODECOV_TOKEN -f "$APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml" `
          } catch { Write-Host "Failed to post Windows codecov" }

    cache:
      - '%MAVEN_HOME% -> pom.xml'
      - '%UserProfile%\.m2 -> pom.xml'

  # LINUX BUILD #
  -
    matrix:
      only:
        - job_name: Linux build

    install:
      - sh: sudo apt-get -y install libcanberra-gtk-module
      - sh: wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.tar.gz -P /tmp &&
          sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt &&
          sudo update-alternatives --install /usr/bin/mvn mvn /opt/apache-maven-3.6.3/bin/mvn 363
      - sh: Xvfb :99 &>/dev/null &
          export DISPLAY=:99

    build_script:
      # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
      - sh: mvn clean verify -Dbuild.version=1.0.0.$APPVEYOR_BUILD_NUMBER

    on_finish:
      - sh: |
          if [ -d "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi
      - sh: |
          if [ -d "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi

    on_failure:
      - sh: |
          if [ -d "$APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged" ]; then appveyor PushArtifact "$APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged"; fi

    on_success:
      - sh: if [ -f "$APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$APPVEYOR_BUILD_NUMBER" ]; then appveyor PushArtifact "$APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$APPVEYOR_BUILD_NUMBER"; else echo "Failed to locate $APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$APPVEYOR_BUILD_NUMBER"; fi
      - sh: curl -Os https://uploader.codecov.io/latest/linux/codecov &&
          chmod +x codecov &&
          ./codecov -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml || echo "Failed to post Linux codecov"

    cache:
      - $HOME/.m2 -> pom.xml

  # MAC BUILD #
  -
    matrix:
      only:
        - job_name: Mac build

    install:
      - sh: export HOMEBREW_NO_INSTALL_CLEANUP=1 &&
            export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
      # mvnvm depends on JDK 21.0.2, need to revert default java to jdk 17
      - sh: brew install mvnvm
      - sh: export JAVA_HOME=`/usr/libexec/java_home -v17`

    build_script:
      # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
      # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
      - sh: mvn clean verify -Dbuild.version=1.0.0.$APPVEYOR_BUILD_NUMBER

    on_finish:
      - sh: |
          if [ -d "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi
      - sh: |
          if [ -d "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi

    on_failure:
      - sh: |
          if [ -d "$APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged" ]; then appveyor PushArtifact "$APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged"; fi

    on_success:
      - sh: if [ -f "$APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$APPVEYOR_BUILD_NUMBER" ]; then appveyor PushArtifact "$APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$APPVEYOR_BUILD_NUMBER"; else echo "Failed to locate $APPVEYOR_BUILD_FOLDER/target/rad_shipment_calc-1.0.0.$APPVEYOR_BUILD_NUMBER"; fi
      - sh: curl -Os https://uploader.codecov.io/latest/macos/codecov &&
          chmod +x codecov &&
          ./codecov -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml || echo "Failed to post Mac codecov"

    cache:
      - $HOME/.m2 -> pom.xml

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'target\rad_shipment_calc-*.jar'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - marcsllite@gmail.com
    on_build_status_changed: true