#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}


# branches to build
branches:
  # whitelist
  only:
    - dev

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'
  author: marcsllite@gmail.com        # Start a new build for commit of given user

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  my_variable:
    secure: SikYTKBlWZ9T6Ep9yw85sLN3+5ryqKyc8YzjTZgnK5adhMWMPvme0gMrLTgtG8ah
  matrix:
    - job_name: Windows build
      appveyor_build_worker_image: Visual Studio 2019
      JDK_11: C:\Program Files\OpenJDK\openjdk-11.0.11_9
      MAVEN_363: C:\ProgramData\chocolatey\lib\maven

    - job_name: Linux build
      appveyor_build_worker_image: Ubuntu

    - job_name: Mac build
      appveyor_build_worker_image: macOs

matrix:
  fast_finish: false

for:
  # WINDOWS BUILD #
  -
    matrix:
      only:
        - job_name: Windows build
    
    init:
      ps: choco install -y openjdk11; 
          C:\ProgramData\chocolatey\bin\RefreshEnv;
          choco upgrade -y maven --version=3.6.3;
          C:\ProgramData\chocolatey\bin\RefreshEnv

    install:
      - set JDK_HOME=%JDK_11%
      # JAVA_HOME is used by Maven
      - set JAVA_HOME=%JDK_11%
      - set MAVEN_HOME=%MAVEN_363%
      - set PATH=%JDK_HOME%;%JDK_HOME%\bin;%PATH%

    build_script:
      - cmd: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    test_script:
      - cmd: mvn clean verify -e -X

    on_success:
      - cmd: Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe 
            -Outfile codecov.exe 
            .\codecov.exe

    cache:
      - '%MAVEN_HOME% -> pom.xml'
      - '%UserProfile%\.m2 -> pom.xml'
  
  # LINUX BUILD #
  -
    matrix:
      only:
        - job_name: Linux build
        
    install:

    build_script:
      - sh: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    test_script:
      - sh: mvn clean verify -e -X

    on_success:
      - sh: curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov
            ./codecov

    cache:
      - $HOME/.m2 -> pom.xml
  
  # MAC BUILD #
  -
    matrix:
      only:
        - job_name: Mac build
    
    init:

    install:
      cmd: /usr/libexec/java_home -V 11.0.2

    build_script:
      - sh: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    test_script:
      - sh: mvn clean verify -e -X

    on_success:
      - sh: curl -Os https://uploader.codecov.io/latest/macos/codecov
            chmod +x codecov 
            ./codecov

    cache:
      - $HOME/.m2 -> pom.xml

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - marcsllite@gmail.com
    on_build_status_changed: true